# Generated by Django 3.2.4 on 2021-10-05 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('01b53905-ec01-4398-9e4b-d48517a807fc'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e2166a8a-7a88-48fa-b71b-8444e2dcee2f'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1d321837-a7b9-4147-9906-ec10baa83ec9'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('events', models.ManyToManyField(db_table='teacher_to_event', to='schedule.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.user')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.eventtype'),
        ),
    ]
