# Generated by Django 3.2.4 on 2021-10-11 19:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b806dd6d-4de9-4b3d-a11a-fc44e2257bfe'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'event_template',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3038f17f-3a14-4ea3-a6c8-3141d02c6322'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('15d48c6f-b424-43cc-93f8-813cae28ad76'), primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06f8ab69-b2f0-4e7b-b636-afd20c68ff43'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('37228f1b-5b6b-40a4-8134-d062fa50b4d2'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.user'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.user'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.eventtemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.role'),
            preserve_default=False,
        ),
    ]
