GROUPS_URL = 'http://rozklad.kpi.ua/Schedules/ScheduleGroupSelection.aspx/GetGroups'
SCHEDULE_URL = 'http://rozklad.kpi.ua/Schedules/ScheduleGroupSelection.aspx?'
VIEWSTATE = '/wEMDAwQAgAADgEMBQAMEAIAAA4BDAUDDBACAAAOAgwFBwwQAgwPAgEIQ3NzQ2xhc3MBD2J0biBidG4tcHJpbWFyeQEEXyFTQgUCAAA' \
            'ADAUNDBACAAAOAQwFAQwQAgAADgMMBQUMEAIMDwICAAABC21vYmlsZS1mb250AgIABQIAAAAMBQcMEAIPAQEaQ29tcGxldGlvbkxpc' \
            '3RJdGVtQ3NzQ2xhc3MCAwAAAAwFDQwQAgwPAwEEVGV4dAEb0KDQvtC30LrQu9Cw0LQg0LfQsNC90Y/RgtGMAgAAAgMAAgIABQIAAA' \
            'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB9fAujPt/SsJ9t2yXnIeyRiM00d '
EVENTVALIDATION = '/wEdAAEAAAD/////AQAAAAAAAAAPAQAAAAUAAAAIsA3rWl3AM+6E94I5Tu9cRJoVjv0LAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' \
                  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' \
                  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' \
                  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHfLZVQO6kVoZVPGurJN4JJIAuaU'
TOOLKITSCRIPTMANAGER = ';;AjaxControlToolkit, Version=3.5.60623.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e' \
                       '::834c499a-b613-438c-a778-d32ab4976134:22eca927:ce87be9:2d27a0fe:23389d96:77aedcab:1bd6c8d4:' \
                       '7b704157'
COMMONTOOLKITSCRIPTS = 1
SCHEDULE = 'Розклад занять'

