
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.9.8
          name: rabbitmq
          ports:
            - containerPort: 5673
          resources:
            limits:
              memory: 512Mi
              cpu: "0.2"
            requests:
              memory: 256Mi
              cpu: "0.2"