# Generated by Django 3.2.4 on 2021-10-11 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_rename_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('deadline_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
            ],
            options={
                'db_table': 'course_assignment',
            },
        ),
        migrations.CreateModel(
            name='CourseAssignmentSubmission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.courseassignment')),
            ],
            options={
                'db_table': 'course_assignment_submission',
            },
        ),
        migrations.CreateModel(
            name='CourseAssignmentSubmissionReview',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('reviewed_at', models.DateTimeField()),
                ('mark', models.IntegerField()),
            ],
            options={
                'db_table': 'course_assignment_submission_review',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.chat')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('68962706-0e28-4bdf-bce4-13c3e384dfc0'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4a4d0ee8-d669-42a7-b0e6-e15b50b9e957'), primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.chat')),
            ],
            options={
                'db_table': 'user_chat',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf9f5680-3f3d-404a-a306-266d58041847'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08b048b6-3e6d-4f6f-909f-86c66e071e91'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='StudentGroup',
        ),
        migrations.AddField(
            model_name='userchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.user'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learn.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.user'),
        ),
        migrations.AddField(
            model_name='courseassignmentsubmissionreview',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.student'),
        ),
        migrations.AddField(
            model_name='courseassignmentsubmissionreview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.courseassignmentsubmission'),
        ),
        migrations.AddField(
            model_name='courseassignmentsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='learn.role'),
            preserve_default=False,
        ),
    ]
