# Generated by Django 3.2.4 on 2021-10-10 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_rename_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d23508f6-bdc3-47c7-bbed-8d610051162e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.group'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23e98e2e-c402-4d8c-8eb6-8f26c957b089'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8636d3bd-6fc6-47dc-8e06-4bc926d66080'), primary_key=True, serialize=False),
        ),
    ]
