# Generated by Django 3.2.4 on 2021-10-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20211011_2128'),
        ('learn', '0008_student_group_switched_to_foreign_key_group'),
    ]

    operations = [
    ]
