# Generated by Django 3.2.4 on 2021-10-30 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_user_avatar_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(db_table='user_role', to='learn.Role'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e32e07d-ac22-4193-b51f-be441a1a0387'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b3a84fde-e42b-4f77-98b7-a3ba6452e466'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a39bb99-d567-4dfa-908f-684ac14f7953'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a2b868a-6c98-4b73-ab64-4e7005b4d653'), primary_key=True, serialize=False),
        ),
    ]
