# Generated by Django 3.2.4 on 2021-09-30 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2515f01d-6c13-4802-8064-431509157bb6'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c07c45b4-0282-414d-9026-333b1c822aaf'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7659e23a-19d6-49bb-a74e-d687093e8a66'), primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.user')),
            ],
        ),
    ]
