# Generated by Django 3.2.4 on 2021-10-01 11:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1e25c2d7-097c-4d4e-aad2-966d5fceab9f'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('formed_at_year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('151c0946-e986-4308-936b-9651f3b1fadf'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d47495a9-d97d-4570-b921-26d811eebda1'), primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.user')),
            ],
        ),
    ]
