# Generated by Django 3.2.4 on 2021-10-03 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_student_group_user_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0039ab4b-271a-401c-901f-371e9ff73ce5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ffac9fd6-4070-4ee0-8e9e-75f0bb7990f8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d55a08c8-e4fc-40da-80bf-ed1108eee24e'), primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='studentgroup',
            table='student_group',
        ),
    ]
