# Generated by Django 3.2.4 on 2021-10-03 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_student_group_user_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ff6ffaa-54f3-4192-b400-1d586a4bd417'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bcd200b7-0b7d-4bb6-b9ae-7803a3f01d21'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d04476bd-e571-4270-8216-7837b08acf58'), primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='studentgroup',
            table='studentGroup',
        ),
    ]
