# Generated by Django 3.2.4 on 2021-10-21 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_merge_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a64ae565-dc56-4ffa-b57c-258c37c5a5fe'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d4cef31-62af-404f-aaa9-4ac1a2476bb7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d9c5a99-b975-4374-9374-c966ca169482'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b476107-7bbe-4324-a6cd-2740673d7f28'), primary_key=True, serialize=False),
        ),
    ]
