version: '3.4'

services:
  campus_learn_db:
    image: postgres:13.4
    container_name: campus_learn_db
    restart: always
    ports:
      - 7433:5432
    networks:
      - campus-learn-network
    env_file:
      - ../.env/learn.env
    volumes:
      - campus-learn-db-data:/var/lib/postgresql/data

  campus_users_db:
    image: postgres:13.4
    container_name: campus_users_db
    restart: always
    ports:
      - 7434:5432
    networks:
      - campus-users-network
    env_file:
      - ../.env/users.env
    volumes:
      - campus-users-db-data:/var/lib/postgresql/data

  campus_gateway_api:
    container_name: campus_gateway_api
    build: 
      context: ../services/GatewayApi
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - campus-learn-network
    environment:
      - Services__Hosts__Learn=http://host.docker.internal:8100

volumes:
  campus-learn-db-data:
    driver: local
  campus-users-db-data:
    driver: local

networks:
  campus-learn-network:
    driver: bridge
  campus-users-network:
    driver: bridge
