version: '3.4'

services:
  campus_learn_db:
    image: postgres:13.4
    container_name: campus_learn_db
    restart: always
    ports:
      - 7433:5432
    networks:
      - campus-learn-network
    env_file:
      - ./.env/learn.env
    volumes:
      - campus-learn-db-data:/var/lib/postgresql/data

  campus_api_gateway:
    container_name: campus_api_gateway
    build: 
      context: ../.kong
    volumes:
      - ../.kong/kong.services.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - 9000:8000 # Listener
      - 9443:8443 # Admin API
      - 127.0.0.1:9001:8001
      - 127.0.0.1:9444:8444
    networks:
      - campus-learn-network
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PLUGINS=bundled

  campus_api_gateway_ui:
    container_name: campus_api_gateway_ui
    image: pocketdigi/kong-admin-ui:0.5.3
    ports:
      - 9899:80
    depends_on:
      - campus_api_gateway
    networks:
      - campus-learn-network

volumes:
  campus-learn-db-data:
    driver: local

networks:
  campus-learn-network:
    driver: bridge
