version: '3.4'

services:
  # Databases
  campus_learn_db:
    container_name: campus_learn_db
    image: postgres:13.4
    restart: on-failure
    ports:
      - 7433:5432
    networks:
      - campus-learn-network
    env_file:
      - ../.env/learn.env
    volumes:
      - campus-learn-db-data:/var/lib/postgresql/data

  campus_users_db:
    image: postgres:13.4
    container_name: campus_users_db
    restart: on-failure
    ports:
      - 7434:5432
    networks:
      - campus-users-network
    env_file:
      - ../.env/users.env
    volumes:
      - campus-users-db-data:/var/lib/postgresql/data

  # Gateway API
  campus_gateway_api:
    container_name: campus_gateway_api
    build: 
      context: ../services/GatewayApi
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - campus-learn-network
      - campus-users-network
    links:
      - campus_users_api:campus-users-api
    environment:
      - Services__Hosts__Learn=http://host.docker.internal:8100
      - Services__Hosts__Users=http://campus-users-api:8200

  campus_users_api:
    container_name: campus_users_api
    build: 
      context: ../services/Users
    restart: on-failure
    ports:
      - 8200:8200
    networks:
      - campus-users-network
    links:
      - campus_event_bus:campus-event-bus
    environment:
      - UrlsOptions__GatewayApiUrl=http://localhost:8200
      - RabbitMQOptions__HostName=campus-event-bus
      - RabbitMQOptions__Port=5673
      - RabbitMQOptions__QueueName=campus
      - RabbitMQOptions__BrokerName=campus_event_bus
      - ASPNETCORE_URLS=http://0.0.0.0:8200
    env_file:
      - ../.env/users.env
    depends_on:
      - campus_event_bus
  
  # Event Bus
  campus_event_bus:
    container_name: campus_event_bus
    image: rabbitmq:3.9.8-management
    restart: on-failure
    ports:
      - 7673:5673
      - 15672:15672
    networks:
      - campus-learn-network
      - campus-users-network
    volumes:
      - ../.rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

volumes:
  campus-learn-db-data:
    driver: local
  campus-users-db-data:
    driver: local

networks:
  campus-learn-network:
    driver: bridge
  campus-users-network:
    driver: bridge
