version: '3.4'

services:
  campus_learn_db:
    image: postgres:13.4
    container_name: campus_learn_db
    restart: always
    ports:
      - 7433:5432
    networks:
      - campus-learn-network
    env_file:
      - ../.env/learn.env
    volumes:
      - campus-learn-db-data:/var/lib/postgresql/data

  campus_learn_api:
    container_name: campus_learn_api
    build: 
      context: ../services/learn
    restart: on-failure
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate learn
        python manage.py runserver
    depends_on:
      - campus_learn_db
    ports:
      - 8100:8100
    networks:
      - campus-learn-network
    env_file:
      - ../.env/learn.env
    environment:
      - ALLOWED_HOST=*
      - DB_HOST=campus_learn_db
      - DB_PORT=5432

  campus_gateway_api:
    container_name: campus_gateway_api
    build: 
      context: ../services/GatewayApi
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - campus-learn-network
    links:
      - campus_learn_api:campus-learn-api
    environment:
      - Services__Hosts__Learn=http://campus-learn-api:8100

  campus_frontend:
    container_name: campus_frontend
    build: 
      context: ../frontend
      args:
        REACT_APP_API_URL: http://localhost:8000/api
    restart: on-failure
    depends_on:
      - campus_learn_api
    ports:
      - 80:80
    networks:
      - campus-learn-network


volumes:
  campus-learn-db-data:
    driver: local

networks:
  campus-learn-network:
    driver: bridge
