version: '3.4'

services:
  campus-learn-db:
    image: postgres:13.4
    container_name: campus_learn_db
    ports:
      - 7433:5432
    env_file:
      - ../.env/learn_db.env
    volumes:
      - campus-learn-db-data:/var/lib/postgresql/data

volumes:
  campus-learn-db-data:
    driver: local