version: '3.4'

services:
  campus-learn-db:
    image: postgres:13.4
    container_name: campus_learn_db
    ports:
      - 7433:5432
    env_file:
      - ../.env/learn.env
    volumes:
      - campus-learn-db-data:/var/lib/postgresql/data

  campus-schedule-db:
    image: postgres:13.4
    container_name: campus_schedule_db
    ports:
      - 7434:5432
    env_file:
      - ../.env/schedule.env
    volumes:
      - campus-schedule-db-data:/var/lib/postgresql/data

volumes:
  campus-learn-db-data:
    driver: local
  campus-schedule-db-data:
    driver: local