version: '3.4'

services:
  campus_learn_api:
    container_name: campus_learn_api
    build: 
      context: ../services/learn
      dockerfile: Dockerfile.k8s-build
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate learn
        python manage.py runserver
    ports:
      - 8000:8000

  campus_gateway_api:
    container_name: campus_gateway_api
    build: 
      context: ../services/GatewayApi

  campus_users_api:
    container_name: campus_users_api
    build: 
      context: ../services/Users

  campus_frontend:
    container_name: campus_frontend
    build:
      context: ../frontend/
      dockerfile: Dockerfile.k8s-build
      args:
        REACT_APP_API_URL: '/api'
