apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
     labels:
       app: frontend
    spec:
      containers:
        - image: docker_campus_frontend:latest
          imagePullPolicy: Never
          name: frontend
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.2"